"""
Runs the B4/B5/B6 LLM-judge baselines (omitbench/judges.py) over the
OmitBench corpus.

Three judges, three model families, ALL via OpenRouter as of 2026-08-13 --
see the JUDGES registry in judges.py for the model/provider justification
for each, and its "UPDATE 2026-08-13" note for why B6 no longer talks to
NVIDIA NIM directly (we hold OPENROUTER_API_KEY, not a direct NVIDIA key):
  B4  openai/gpt-oss-120b            via OpenRouter, pinned to Cerebras fp16
  B5  mistralai/mistral-medium-3     via OpenRouter, pinned to Mistral (first-party)
  B6  nvidia/nemotron-3-super-120b-a12b via OpenRouter, pinned to DeepInfra bf16

Two run modes (TASKS.md T1), same as before, now applied per judge:
  (a) k=1 over the full corpus            -> the headline number.   --k 1
  (b) k=5 over a STRATIFIED 100-instance
      subsample (by repo and mutation)     -> std dev of MCC across
                                               seeds.                --k 5

Never runs k=5 over the full corpus -- five times the cost, answers the same
question (a)+(b) already answer between them.

--dry-run prints the estimated call count and spend per judge and makes NO
API call. --max-cost hard-fails DURING a real run before cumulative spend
(summed across every judge in this invocation) exceeds it, using each call's
REAL reported cost (OpenRouter's usage.cost) or, for NIM, a labelled
estimate -- see judges.py::_extract_cost. Nothing here estimates OpenRouter
spend during a real run; only --dry-run estimates, and only because no call
has been made yet to report a real number.

Output:
  k=1  -> results/shards/llm_judge_<judge-slug>.jsonl
          One file per judge, so three judges never overwrite each other and
          scripts/analyze.py picks all three up automatically -- no code
          change needed there once these files exist.
  k=5  -> results/k5_subsample/llm_judge_<judge-slug>_seed{N}.jsonl
          Deliberately OUTSIDE results/shards/: analyze.py must never
          average five duplicated seeds of the same 100 instances into the
          headline table. Read the std dev with scripts/k5_variance.py.

Requires `pip install -e .[judge]` and network + OPENROUTER_API_KEY (all
three judges) for anything beyond --dry-run.

CORPUS ALIGNMENT. `results/shards/*.jsonl` (what P0/P1/P2/P3 were scored
against) is generated by `make pilot` -> scripts/run_shards.sh, which
invokes `omitbench.experiment` as ONE SUBPROCESS PER REPO. This script must
build the identical set of instances for the same (seed, scan-cap, per-repo)
or a judge ends up scored against a different sample than the other
detectors, silently breaking analyze.py's paired-bootstrap assumption of
identical iid coverage across every detector. check_alignment() (also
reachable standalone via --check-alignment) verifies this by asserting a
judge-corpus build's iids are a SUBSET of the shards' iids, and runs
automatically before any real sweep -- there is no path to spending money
that skips it. See build_instances()'s docstring for a defect of exactly
this shape (multi-repo calls silently drawing the wrong commits) that this
check exists to catch, found and fixed while wiring it up.

    make pilot                                            # regenerate the shards
    python3 scripts/run_judge.py --check-alignment --repos corpus/*   # verify, no spend
    python3 scripts/run_judge.py --repos corpus/* --limit-instances 20 ...  # then spend
"""

from __future__ import annotations

import argparse
import gc
import glob
import json
import os
import random
import sys
from collections import defaultdict

sys.path.insert(0, ".")

from omitbench import experiment as E  # noqa: E402
from omitbench import judges as J  # noqa: E402
from omitbench import mutate as M  # noqa: E402

# Short codes accepted on --judges, resolved against J.JUDGES keys by prefix
# match ("B4" -> "B4 LLM judge (gpt-oss-120b)") so the CLI doesn't require
# typing the full parenthesised name.
_SHORT_CODES = {"B4": "B4 LLM judge (gpt-oss-120b)",
                "B5": "B5 LLM judge (mid-tier)",
                "B6": "B6 LLM judge (NVIDIA NIM)"}

# Placeholder average per-call token counts, used ONLY for --dry-run when no
# real per-instance measurement is available. This is a stated ASSUMPTION,
# not a measurement -- a real 20-instance run (--limit-instances 20) reports
# the actual numbers, which should replace these before trusting a cost
# estimate for the full sweep. Same assumed tokens for every judge: the
# prompt is identical across judges (build_prompt is shared), so this is a
# property of the corpus, not of any one backend.
FALLBACK_AVG_INPUT_TOKENS = 700    # prompt template + reqs + a typical diff
FALLBACK_AVG_OUTPUT_TOKENS = 120   # small JSON object, median 2 reqs/variant


def _resolve_judges(names: list[str]) -> list[J.JudgeConfig]:
    out = []
    for n in names:
        key = _SHORT_CODES.get(n.upper(), n)
        if key not in J.JUDGES:
            sys.exit(f"unknown judge {n!r}; choose from "
                      f"{sorted(_SHORT_CODES)} or {sorted(J.JUDGES)}")
        out.append(J.JUDGES[key])
    return out


def _report_pins(cfgs: list[J.JudgeConfig]) -> None:
    """Item: 'Report the pinned provider slug and the reasoning setting
    before the sweep.' Printed unconditionally -- dry run or real -- so it
    can never be missed in either mode's output.
    """
    print("judge configuration (pinned provider / reasoning setting):",
          file=sys.stderr)
    for cfg in cfgs:
        prov = cfg.provider_slug or "(not brokered -- NIM, nothing to pin)"
        reas = cfg.reasoning_effort or "(no reasoning-depth knob set)"
        print(f"  {cfg.judge_id:32} model={cfg.model_slug:32} "
              f"provider={prov:16} reasoning={reas}", file=sys.stderr)
    print(file=sys.stderr)


def _shard_records():
    for p in sorted(glob.glob("results/shards/*.jsonl")):
        with open(p) as f:
            for line in f:
                if line.strip():
                    yield json.loads(line)


def corpus_variant_counts():
    """Exact (iid, mutation) variant counts from the already-committed pilot
    shards -- the same corpus this sweep targets. Lets --dry-run give an
    exact call count without a fresh `make corpus` checkout (network, ~25
    min); it is not needed for counting, only for the real run's diffs.
    """
    seen = set()
    by_iid_mutations: dict[str, set] = defaultdict(set)
    repo_of: dict[str, str] = {}
    first_detector = None
    for r in _shard_records():
        if first_detector is None:
            first_detector = r["detector"]
        if r["detector"] != first_detector:
            continue  # count each (iid, mutation) once, not once per detector
        seen.add((r["iid"], r["mutation"]))
        by_iid_mutations[r["iid"]].add(r["mutation"])
        repo_of[r["iid"]] = r["repo"]
    return seen, by_iid_mutations, repo_of


def estimate_one(cfg, k, subsample, avg_in, avg_out, n_variants, n_instances):
    if k == 1:
        calls = n_variants
    else:
        n_inst = min(subsample, n_instances)
        avg_variants_per_instance = n_variants / max(1, n_instances)
        calls = round(n_inst * avg_variants_per_instance) * 5  # k=5 seeds
    pin, pout = cfg.dry_run_price_per_1m
    cost = calls * (avg_in * pin + avg_out * pout) / 1_000_000
    return calls, cost


def stratified_subsample(rng, target=100):
    """~`target` INSTANCES (not rows), stratified by (repo, sorted tuple of
    mutation classes that instance produced) -- the closest available proxy
    for "by repo and by mutation class" when mutation class is a property of
    an instance's variants, not of the instance itself. Sampling instances
    (rather than rows) matches the cluster-bootstrap unit in analyze.py.
    """
    _, by_iid, repo_of = corpus_variant_counts()
    strata: dict[tuple, list] = defaultdict(list)
    for iid, muts in by_iid.items():
        strata[(repo_of[iid], tuple(sorted(muts)))].append(iid)
    total = len(by_iid)
    chosen: list[str] = []
    for key, members in strata.items():
        share = max(1, round(target * len(members) / total))
        chosen.extend(rng.sample(members, min(share, len(members))))
    rng.shuffle(chosen)
    return set(chosen[:target])


def _missing_keys(cfgs: list[J.JudgeConfig]) -> list[str]:
    envs = {cfg.api_key_env for cfg in cfgs}
    return sorted(e for e in envs if not os.environ.get(e))


def build_instances(repos, per_repo, seed, scan_cap):
    """E.build(repo_list, ...) creates exactly ONE random.Random(seed) and
    reuses it across every repo in the list, shuffling each repo's commits
    in sequence from wherever that shared RNG's state happens to be.
    results/shards/*.jsonl was generated by scripts/run_shards.sh, which
    invokes `omitbench.experiment` as ONE SUBPROCESS PER REPO -- so every
    repo there gets build()'s internal random.Random(seed) FRESH. Passing
    the whole --repos list to E.build() in a single call, as this script
    used to, reproduces that only for the FIRST repo in the list; every
    other repo silently draws a different sample of commits, and the
    'judge iids subset of shard iids' invariant this file's alignment check
    exists to enforce breaks the moment more than one repo is passed. Fix:
    call build() once per repo, exactly mirroring run_shards.sh, so the
    RNG is reseeded fresh for each one.
    """
    insts = []
    for repo in repos:
        insts.extend(E.build([repo], per_repo, seed, scan_cap))
        # CLAUDE.md: "mutate.py memoises AST parses in module-level dicts. A
        # multi-repo run OOMs without clearing them between repos." That's
        # exactly what this loop is -- multiple repos, one process -- and
        # E.build() itself calls into M._defs/call_targets/call_lines while
        # picking candidate symbols, so the memos fill up during THIS call,
        # not just during scoring. experiment.py's own multi-repo entry
        # point (main(), driving scripts/run_shards.sh) clears these after
        # every repo for the same reason; this is that same fix applied
        # here, since run_shards.sh's other workaround -- one OS subprocess
        # per repo -- doesn't apply to an in-process loop like this one.
        for memo in (M._TREE_MEMO, M._DEF_MEMO, M._CALL_MEMO, M._TARGETS_MEMO):
            memo.clear()
        gc.collect()
    return insts


def check_alignment(insts, limit=20) -> None:
    """Print iid counts from results/shards/*.jsonl vs the first `limit`
    instances of an already-built judge corpus (pure instance construction
    -- build_instances() never calls a judge or spends anything), and hard-
    fail unless the judge's iids are a SUBSET of the shards'. A non-subset
    result means run_judge.py and whatever generated the shards are drawing
    different commits for the same (seed, scan-cap, per-repo) -- see
    build_instances()'s docstring for the specific defect this caught. Run
    this BEFORE any API call: a mismatch here means the judge would be
    scored against instances the P1/P3 baselines never saw, which breaks
    analyze.py's paired-bootstrap assumption of identical iid coverage
    across every detector -- silently, unless caught here first.

    Takes already-built `insts` rather than building its own, so the
    mandatory real-run pre-flight and the standalone --check-alignment path
    both reuse ONE build (per-repo corpus construction is not free) instead
    of paying for it twice.
    """
    _, shard_by_iid, _ = corpus_variant_counts()
    shard_iids = set(shard_by_iid)

    judge_iids = {i[0] for i in insts[:limit]}
    inter = judge_iids & shard_iids

    print(f"iid count, results/shards/*.jsonl   {len(shard_iids)}")
    print(f"iid count, {limit}-instance judge build   {len(judge_iids)}")
    print(f"intersection                        {len(inter)}")

    if not judge_iids.issubset(shard_iids):
        missing = sorted(judge_iids - shard_iids)[:10]
        sys.exit(
            f"ALIGNMENT CHECK FAILED: {len(judge_iids - shard_iids)} of "
            f"{len(judge_iids)} judge iids are NOT in results/shards/*.jsonl "
            f"(e.g. {missing}). run_judge.py's instance build and whatever "
            f"produced the shards (scripts/run_shards.sh -> "
            f"omitbench.experiment) are using different seed/scan-cap/"
            f"per-repo values, or a different repo-call pattern -- see "
            f"build_instances()'s docstring for a defect of exactly this "
            f"shape that was found and fixed here. Fix this before spending "
            f"anything.")
    print("alignment check passed: judge iids are a subset of shard iids\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--repos", nargs="+",
                     help="corpus/<repo> dirs to build instances from "
                          "(required for a real run; not needed for --dry-run)")
    ap.add_argument("--judges", nargs="+", default=["B4", "B5", "B6"],
                     help="which judges to run: short codes B4/B5/B6 or full "
                          "DETECTORS keys (default: all three)")
    ap.add_argument("--per-repo", type=int, default=40)
    ap.add_argument("--scan-cap", type=int, default=600)
    ap.add_argument("--k", type=int, choices=[1, 5], default=1)
    ap.add_argument("--subsample", type=int, default=100)
    ap.add_argument("--seeds", type=int, nargs="+", default=[0, 1, 2, 3, 4])
    ap.add_argument("--max-cost", type=float, default=5.0,
                     help="hard-fail mid-run before cumulative spend (summed "
                          "across every judge run in this invocation) "
                          "exceeds this many USD")
    ap.add_argument("--dry-run", action="store_true",
                     help="print the estimated call count and spend per "
                          "judge; make NO API call")
    ap.add_argument("--check-alignment", action="store_true",
                     help="print shard/judge iid counts and their "
                          "intersection, assert the judge's are a subset of "
                          "the shards', then exit. Pure instance "
                          "construction -- no judge or API call. Also runs "
                          "automatically before any real (non-dry-run) "
                          "sweep, so this flag is for running it standalone, "
                          "e.g. right after `make pilot`.")
    ap.add_argument("--alignment-check-instances", type=int, default=20,
                     help="instance count for --check-alignment / the "
                          "automatic pre-flight check")
    ap.add_argument("--avg-input-tokens", type=float, default=FALLBACK_AVG_INPUT_TOKENS)
    ap.add_argument("--avg-output-tokens", type=float, default=FALLBACK_AVG_OUTPUT_TOKENS)
    ap.add_argument("--limit-instances", type=int, default=None,
                     help="debug: cap instances scored, e.g. 20 for a pilot sample")
    ap.add_argument("--out-dir", default=None,
                     help="override output directory (debug only; default "
                          "is results/shards or results/k5_subsample)")
    a = ap.parse_args()

    cfgs = _resolve_judges(a.judges)
    _report_pins(cfgs)

    if a.dry_run:
        variants, by_iid, _ = corpus_variant_counts()
        n_variants, n_instances = len(variants), len(by_iid)
        mode = ("k=1 over the full corpus" if a.k == 1
                else f"k={a.k} over a stratified ~{a.subsample}-instance subsample")
        print(f"mode              {mode}")
        print(f"full corpus       {n_instances} instances, {n_variants} "
              f"(iid, mutation) variants (from results/shards/*.jsonl)")
        print(f"assumed tokens    {a.avg_input_tokens:.0f} in / "
              f"{a.avg_output_tokens:.0f} out per call  "
              f"[ASSUMPTION -- not measured; override with "
              f"--avg-input-tokens/--avg-output-tokens from a real "
              f"--limit-instances 20 run before trusting this estimate]\n")
        total_calls = total_cost = 0
        for cfg in cfgs:
            calls, cost = estimate_one(cfg, a.k, a.subsample,
                                        a.avg_input_tokens, a.avg_output_tokens,
                                        n_variants, n_instances)
            total_calls += calls
            total_cost += cost
            print(f"  {cfg.judge_id:32} calls {calls:>6}   "
                  f"est. cost ${cost:>7.2f}  "
                  f"(list price ${cfg.dry_run_price_per_1m[0]:.2f}/"
                  f"${cfg.dry_run_price_per_1m[1]:.2f} per 1M in/out"
                  f"{', NIM estimate' if cfg.nim_price_per_1m else ''})")
        print(f"\n  {'TOTAL':32} calls {total_calls:>6}   "
              f"est. cost ${total_cost:>7.2f}   (--max-cost ${a.max_cost:.2f})")
        print("\nNO API call was made.")
        if total_cost > a.max_cost:
            print("This WOULD hard-fail: estimated total cost exceeds --max-cost.")
        return

    if not a.repos:
        sys.exit("--repos is required (see `make corpus`)")

    insts = build_instances(a.repos, a.per_repo, a.seeds[0], a.scan_cap)

    if a.check_alignment:
        check_alignment(insts, a.alignment_check_instances)
        return

    missing = _missing_keys(cfgs)
    if missing:
        sys.exit(f"missing environment variable(s) for a real run: "
                  f"{', '.join(missing)}")

    # Mandatory pre-flight, every real run, before any API call: see
    # check_alignment()'s docstring. Not just available via
    # --check-alignment -- structurally impossible to skip on the way to
    # spending anything.
    check_alignment(insts, a.alignment_check_instances)

    rng = random.Random(a.seeds[0])
    if a.k == 5:
        keep = stratified_subsample(rng, a.subsample)
        insts = [i for i in insts if i[0] in keep]
    if a.limit_instances:
        insts = insts[: a.limit_instances]

    seeds = a.seeds if a.k == 5 else [a.seeds[0]]
    spent = 0.0

    for cfg in cfgs:
        slug = J._slugify(cfg.judge_id)
        detector_fn = J.DETECTORS[cfg.judge_id]
        for seed in seeds:
            recs = []
            for iid, rname, spec, before, target, reqs, variants in insts:
                for cls, after in variants:
                    record: dict = {}
                    ctx = {"_judge_record": record}
                    if a.k == 5:
                        # Only the k=5 variance path sets this. It folds
                        # into judges.py's cache key so seeds 2-5 don't
                        # cache-hit seed 1's response for the identical
                        # prompt -- see the VARIANCE SEED comment above
                        # judges.py::_cache_key. The k=1 headline sweep
                        # never sets it, so its cache keys are byte-
                        # identical to before this existed.
                        ctx["_variance_seed"] = seed
                    try:
                        preds = detector_fn(spec, reqs, before, after, ctx)
                    except Exception as e:
                        print(f"  ERROR {cfg.judge_id}/{iid}/{cls}: {e!r}",
                              file=sys.stderr)
                        continue
                    if not record.get("cache_hit") and record.get("cost_usd") is not None:
                        spent += record["cost_usd"]
                    if spent > a.max_cost:
                        sys.exit(f"HARD STOP: spent ${spent:.2f} exceeds "
                                 f"--max-cost ${a.max_cost:.2f} "
                                 f"(cumulative across all judges this run)")
                    for r in reqs:
                        gold = "OMITTED" if (cls != "CLEAN" and r == target) \
                               else "IMPLEMENTED"
                        recs.append({
                            "iid": iid, "repo": rname, "req": r, "target": target,
                            "mutation": cls, "detector": cfg.judge_id,
                            "pred": preds.get(r, "IMPLEMENTED"), "gold": gold,
                            "seed": seed,
                            "model_slug": record.get("model_slug"),
                            "provider_pinned": record.get("provider_pinned"),
                            "provider_returned": record.get("provider_returned"),
                            "reasoning_effort": record.get("reasoning_effort"),
                            "truncated": record.get("truncated", False),
                            "parse_failed": record.get("parse_failed", False),
                            "parsed_from_field": record.get("parsed_from_field"),
                            "cache_hit": record.get("cache_hit", False),
                            "cost_usd": record.get("cost_usd"),
                            "cost_source": record.get("cost_source"),
                        })
            out_dir = a.out_dir or ("results/shards" if a.k == 1 else "results/k5_subsample")
            out = os.path.join(out_dir, f"llm_judge_{slug}.jsonl" if a.k == 1
                                else f"llm_judge_{slug}_seed{seed}.jsonl")
            os.makedirs(out_dir, exist_ok=True)
            with open(out, "w") as f:
                for r in recs:
                    f.write(json.dumps(r) + "\n")
            print(f"{cfg.judge_id} seed {seed}: {len(recs)} records -> {out}",
                  file=sys.stderr)

        stats = J._stats_for(cfg.judge_id)
        pf, calls = stats.parse_failures, max(1, stats.calls)
        print(f"  {cfg.judge_id}: calls {stats.calls} | cache hits "
              f"{stats.cache_hits} | parse failures {pf}/{calls} calls "
              f"({pf / calls:.1%}) | truncated {stats.truncated} | "
              f"retries {stats.retries}", file=sys.stderr)

    print(f"\ncumulative spend across all judges this run: ${spent:.2f}",
          file=sys.stderr)


if __name__ == "__main__":
    main()
